export const USER_LOGINS = 'USER_LOGINS';
export const USER_LOGINS_API = 'USER_LOGINS_API';
export const USER_INFO = 'USER_INFO';
export const USER_INFO_API = 'USER_INFO_API';
export const USER_INPUT = 'USER_INPUT';
export const NOTIFICATIONS_DISPLAY_MESSAGE = "NOTIFICATIONS_DISPLAY_MESSAGE";
export const NOTIFICATIONS_CLEAR_MESSAGE = "NOTIFICATIONS_CLEAR_MESSAGE";
